FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS wordpressdata;
CREATE USER 'jsilance'@'%' IDENTIFIED BY 'jsilance';
GRANT ALL PRIVILEGES ON *.* TO 'jsilance'@'%' IDENTIFIED BY 'jsilance' WITH GRANT OPTION;
FLUSH PRIVILEGES;