apiVersion: v1
kind: Service
metadata:
  name: my-ftps
  labels:
    app: my-ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-ftps
  ports:
  - name: ftps0
    protocol: TCP
    port: 21
  - name: ftps1
    protocol: TCP
    port: 21000
  - name: ftps2
    protocol: TCP
    port: 21001
  - name: ftps3
    protocol: TCP
    port: 21002
  - name: ftps4
    protocol: TCP
    port: 21003
  - name: ftps5
    protocol: TCP
    port: 21004
  type: LoadBalancer
  
---
apiVersion: v1
kind: Service
metadata:
  name: my-grafana
  labels:
    app: my-grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-grafana
  ports:
  - protocol: TCP
    port: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-influxdb
  labels:
    app: my-influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-influxdb
  ports:
  - protocol: TCP
    port: 8086
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql
  labels:
    app: my-mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-mysql
  ports:
  - protocol: TCP
    port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-phpmyadmin
  labels:
    app: my-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-webwp
  labels:
    app: my-webwp
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  selector:
    app: my-webwp
  ports:
  - protocol: TCP
    port: 5050
  type: LoadBalancer